library(tidyverse)
library(sf)
library(devtools)
library(roxygen2)
tournament <- read_csv("tournament.csv") %>% subset(select=-c(1))
player_box <- read_csv("player.csv") %>% subset(select=-c(1))
game_locations <- st_read('game_loc.shp')
team_locations <- st_read('team_locations.shp')
use_data(tournament, overwrite = TRUE)
use_data(game_locations, overwrite = TRUE)
use_data(team_locations, overwrite = TRUE)
